name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: yarn test
  needsDocsUpdate:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      - name: Fail if any changes
        if: steps.changes.outputs.changed == 1
        run: |
          echo "Uncommitted build artifacts exist, please check them in."
          exit 1
